allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@types/pg@8.21.0'
  - '@clerk/backend@3.16.1'
  - '@clerk/shared@4.27.1'
  - '@clerk/testing@2.2.19'
