packages:
  - '.'
  - 'collab-server'
allowBuilds:

  '@clerk/shared': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@types/pg@8.21.0'
  - '@clerk/backend@3.16.1'
  - '@clerk/shared@4.27.1'
  - '@clerk/testing@2.2.19'
  - '@clerk/nextjs@7.7.1'
  - '@clerk/react@6.13.1'
